web_controllers:
    resource: ../../src/Controller/Web/
    type: annotation
api_controllers:
    resource: ../../src/Controller/Api/
    type: annotation
    prefix: /api/v1/
    name_prefix: api_

kernel:
    resource: ../../src/Kernel.php
    type: annotation
